-- Auto-generated by wow_randomizer.py export-addon
-- This placeholder keeps addon loadable before first export.

WRL_LootByCreature = WRL_LootByCreature or {}
WRL_CreatureNames = WRL_CreatureNames or {}
WRL_ItemNames = WRL_ItemNames or {}
WRL_Metadata = WRL_Metadata or {
    generated_at = 0,
    creatures = 0,
    entries = 0,
}
